In [1]:
from google.colab import files

uploaded = files.upload()

Saving HDI.csv to HDI.csv

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import pickle

In [5]:
df = pd.read_csv("HDI.csv")

In [6]:
# Read the dataset
df = pd.read_csv("HDI.csv")   # Replace with your dataset name

# Display first 5 rows
df.head()

,ISO3,Country,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Human Development Index (1990),Human Development Index (1991),Human Development Index (1992),Human Development Index (1993),Human Development Index (1994),...,Material footprint per capita (tonnes) (2012),Material footprint per capita (tonnes) (2013),Material footprint per capita (tonnes) (2014),Material footprint per capita (tonnes) (2015),Material footprint per capita (tonnes) (2016),Material footprint per capita (tonnes) (2017),Material footprint per capita (tonnes) (2018),Material footprint per capita (tonnes) (2019),Material footprint per capita (tonnes) (2020),Material footprint per capita (tonnes) (2021)
0,AFG,Afghanistan,Low,SA,180.0,0.273,0.279,0.287,0.297,0.292,...,1.86,1.88,1.66,1.62,1.66,1.41,1.32,1.38,1.38,1.38
1,AGO,Angola,Medium,SSA,148.0,NaN,NaN,NaN,NaN,NaN,...,4.09,4.53,3.97,3.59,2.79,2.64,2.28,2.18,2.18,2.18
2,ALB,Albania,High,ECA,67.0,0.647,0.629,0.614,0.617,0.624,...,12.44,11.49,13.14,12.61,14.39,14.46,12.85,12.96,12.96,12.96
3,AND,Andorra,Very High,NaN,40.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ARE,United Arab Emirates,Very High,AS,26.0,0.728,0.739,0.742,0.748,0.755,...,49.56,49.68,55.49,59.76,64.95,75.61,65.97,68.95,68.95,68.95

In [7]:
df.isnull().sum()

ISO3                                              0
Country                                           0
Human Development Groups                          4
UNDP Developing Regions                          44
HDI Rank (2021)                                   4
                                                 ..
Material footprint per capita (tonnes) (2017)    38
Material footprint per capita (tonnes) (2018)    38
Material footprint per capita (tonnes) (2019)    38
Material footprint per capita (tonnes) (2020)    38
Material footprint per capita (tonnes) (2021)    38
Length: 880, dtype: int64

In [8]:
missing_values = df.isnull().sum()
missing_values[missing_values > 0]

Human Development Groups                          4
UNDP Developing Regions                          44
HDI Rank (2021)                                   4
Human Development Index (1990)                   54
Human Development Index (1991)                   54
                                                 ..
Material footprint per capita (tonnes) (2017)    38
Material footprint per capita (tonnes) (2018)    38
Material footprint per capita (tonnes) (2019)    38
Material footprint per capita (tonnes) (2020)    38
Material footprint per capita (tonnes) (2021)    38
Length: 738, dtype: int64

In [9]:
threshold = len(df) * 0.5
df = df.dropna(axis=1, thresh=threshold)

In [10]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [11]:
cat_cols = df.select_dtypes(include=['object']).columns

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [12]:
df.isnull().sum().sum()

np.int64(0)

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Columns: 880 entries, ISO3 to Material footprint per capita (tonnes) (2021)
dtypes: float64(876), int64(4)
memory usage: 1.3 MB

In [15]:
df.columns

Index(['ISO3', 'Country', 'Human Development Groups',
       'UNDP Developing Regions', 'HDI Rank (2021)',
       'Human Development Index (1990)', 'Human Development Index (1991)',
       'Human Development Index (1992)', 'Human Development Index (1993)',
       'Human Development Index (1994)',
       ...
       'Material footprint per capita (tonnes) (2012)',
       'Material footprint per capita (tonnes) (2013)',
       'Material footprint per capita (tonnes) (2014)',
       'Material footprint per capita (tonnes) (2015)',
       'Material footprint per capita (tonnes) (2016)',
       'Material footprint per capita (tonnes) (2017)',
       'Material footprint per capita (tonnes) (2018)',
       'Material footprint per capita (tonnes) (2019)',
       'Material footprint per capita (tonnes) (2020)',
       'Material footprint per capita (tonnes) (2021)'],
      dtype='object', length=880)

In [16]:
print(df.columns.tolist())

['ISO3', 'Country', 'Human Development Groups', 'UNDP Developing Regions', 'HDI Rank (2021)', 'Human Development Index (1990)', 'Human Development Index (1991)', 'Human Development Index (1992)', 'Human Development Index (1993)', 'Human Development Index (1994)', 'Human Development Index (1995)', 'Human Development Index (1996)', 'Human Development Index (1997)', 'Human Development Index (1998)', 'Human Development Index (1999)', 'Human Development Index (2000)', 'Human Development Index (2001)', 'Human Development Index (2002)', 'Human Development Index (2003)', 'Human Development Index (2004)', 'Human Development Index (2005)', 'Human Development Index (2006)', 'Human Development Index (2007)', 'Human Development Index (2008)', 'Human Development Index (2009)', 'Human Development Index (2010)', 'Human Development Index (2011)', 'Human Development Index (2012)', 'Human Development Index (2013)', 'Human Development Index (2014)', 'Human Development Index (2015)', 'Human Development Index (2016)', 'Human Development Index (2017)', 'Human Development Index (2018)', 'Human Development Index (2019)', 'Human Development Index (2020)', 'Human Development Index (2021)', 'Life Expectancy at Birth (1990)', 'Life Expectancy at Birth (1991)', 'Life Expectancy at Birth (1992)', 'Life Expectancy at Birth (1993)', 'Life Expectancy at Birth (1994)', 'Life Expectancy at Birth (1995)', 'Life Expectancy at Birth (1996)', 'Life Expectancy at Birth (1997)', 'Life Expectancy at Birth (1998)', 'Life Expectancy at Birth (1999)', 'Life Expectancy at Birth (2000)', 'Life Expectancy at Birth (2001)', 'Life Expectancy at Birth (2002)', 'Life Expectancy at Birth (2003)', 'Life Expectancy at Birth (2004)', 'Life Expectancy at Birth (2005)', 'Life Expectancy at Birth (2006)', 'Life Expectancy at Birth (2007)', 'Life Expectancy at Birth (2008)', 'Life Expectancy at Birth (2009)', 'Life Expectancy at Birth (2010)', 'Life Expectancy at Birth (2011)', 'Life Expectancy at Birth (2012)', 'Life Expectancy at Birth (2013)', 'Life Expectancy at Birth (2014)', 'Life Expectancy at Birth (2015)', 'Life Expectancy at Birth (2016)', 'Life Expectancy at Birth (2017)', 'Life Expectancy at Birth (2018)', 'Life Expectancy at Birth (2019)', 'Life Expectancy at Birth (2020)', 'Life Expectancy at Birth (2021)', 'Expected Years of Schooling (1990)', 'Expected Years of Schooling (1991)', 'Expected Years of Schooling (1992)', 'Expected Years of Schooling (1993)', 'Expected Years of Schooling (1994)', 'Expected Years of Schooling (1995)', 'Expected Years of Schooling (1996)', 'Expected Years of Schooling (1997)', 'Expected Years of Schooling (1998)', 'Expected Years of Schooling (1999)', 'Expected Years of Schooling (2000)', 'Expected Years of Schooling (2001)', 'Expected Years of Schooling (2002)', 'Expected Years of Schooling (2003)', 'Expected Years of Schooling (2004)', 'Expected Years of Schooling (2005)', 'Expected Years of Schooling (2006)', 'Expected Years of Schooling (2007)', 'Expected Years of Schooling (2008)', 'Expected Years of Schooling (2009)', 'Expected Years of Schooling (2010)', 'Expected Years of Schooling (2011)', 'Expected Years of Schooling (2012)', 'Expected Years of Schooling (2013)', 'Expected Years of Schooling (2014)', 'Expected Years of Schooling (2015)', 'Expected Years of Schooling (2016)', 'Expected Years of Schooling (2017)', 'Expected Years of Schooling (2018)', 'Expected Years of Schooling (2019)', 'Expected Years of Schooling (2020)', 'Expected Years of Schooling (2021)', 'Mean Years of Schooling (1990)', 'Mean Years of Schooling (1991)', 'Mean Years of Schooling (1992)', 'Mean Years of Schooling (1993)', 'Mean Years of Schooling (1994)', 'Mean Years of Schooling (1995)', 'Mean Years of Schooling (1996)', 'Mean Years of Schooling (1997)', 'Mean Years of Schooling (1998)', 'Mean Years of Schooling (1999)', 'Mean Years of Schooling (2000)', 'Mean Years of Schooling (2001)', 'Mean Years of Schooling (2002)', 'Mean Years of Schooling (2003)', 'Mean Years of Schooling (2004)', 'Mean Years of Schooling (2005)', 'Mean Years of Schooling (2006)', 'Mean Years of Schooling (2007)', 'Mean Years of Schooling (2008)', 'Mean Years of Schooling (2009)', 'Mean Years of Schooling (2010)', 'Mean Years of Schooling (2011)', 'Mean Years of Schooling (2012)', 'Mean Years of Schooling (2013)', 'Mean Years of Schooling (2014)', 'Mean Years of Schooling (2015)', 'Mean Years of Schooling (2016)', 'Mean Years of Schooling (2017)', 'Mean Years of Schooling (2018)', 'Mean Years of Schooling (2019)', 'Mean Years of Schooling (2020)', 'Mean Years of Schooling (2021)', 'Gross National Income Per Capita (1990)', 'Gross National Income Per Capita (1991)', 'Gross National Income Per Capita (1992)', 'Gross National Income Per Capita (1993)', 'Gross National Income Per Capita (1994)', 'Gross National Income Per Capita (1995)', 'Gross National Income Per Capita (1996)', 'Gross National Income Per Capita (1997)', 'Gross National Income Per Capita (1998)', 'Gross National Income Per Capita (1999)', 'Gross National Income Per Capita (2000)', 'Gross National Income Per Capita (2001)', 'Gross National Income Per Capita (2002)', 'Gross National Income Per Capita (2003)', 'Gross National Income Per Capita (2004)', 'Gross National Income Per Capita (2005)', 'Gross National Income Per Capita (2006)', 'Gross National Income Per Capita (2007)', 'Gross National Income Per Capita (2008)', 'Gross National Income Per Capita (2009)', 'Gross National Income Per Capita (2010)', 'Gross National Income Per Capita (2011)', 'Gross National Income Per Capita (2012)', 'Gross National Income Per Capita (2013)', 'Gross National Income Per Capita (2014)', 'Gross National Income Per Capita (2015)', 'Gross National Income Per Capita (2016)', 'Gross National Income Per Capita (2017)', 'Gross National Income Per Capita (2018)', 'Gross National Income Per Capita (2019)', 'Gross National Income Per Capita (2020)', 'Gross National Income Per Capita (2021)', 'GDI Group (2021)', 'Gender Development Index (1990)', 'Gender Development Index (1991)', 'Gender Development Index (1992)', 'Gender Development Index (1993)', 'Gender Development Index (1994)', 'Gender Development Index (1995)', 'Gender Development Index (1996)', 'Gender Development Index (1997)', 'Gender Development Index (1998)', 'Gender Development Index (1999)', 'Gender Development Index (2000)', 'Gender Development Index (2001)', 'Gender Development Index (2002)', 'Gender Development Index (2003)', 'Gender Development Index (2004)', 'Gender Development Index (2005)', 'Gender Development Index (2006)', 'Gender Development Index (2007)', 'Gender Development Index (2008)', 'Gender Development Index (2009)', 'Gender Development Index (2010)', 'Gender Development Index (2011)', 'Gender Development Index (2012)', 'Gender Development Index (2013)', 'Gender Development Index (2014)', 'Gender Development Index (2015)', 'Gender Development Index (2016)', 'Gender Development Index (2017)', 'Gender Development Index (2018)', 'Gender Development Index (2019)', 'Gender Development Index (2020)', 'Gender Development Index (2021)', 'HDI female (1990)', 'HDI female (1991)', 'HDI female (1992)', 'HDI female (1993)', 'HDI female (1994)', 'HDI female (1995)', 'HDI female (1996)', 'HDI female (1997)', 'HDI female (1998)', 'HDI female (1999)', 'HDI female (2000)', 'HDI female (2001)', 'HDI female (2002)', 'HDI female (2003)', 'HDI female (2004)', 'HDI female (2005)', 'HDI female (2006)', 'HDI female (2007)', 'HDI female (2008)', 'HDI female (2009)', 'HDI female (2010)', 'HDI female (2011)', 'HDI female (2012)', 'HDI female (2013)', 'HDI female (2014)', 'HDI female (2015)', 'HDI female (2016)', 'HDI female (2017)', 'HDI female (2018)', 'HDI female (2019)', 'HDI female (2020)', 'HDI female (2021)', 'Life Expectancy at Birth, female (1990)', 'Life Expectancy at Birth, female (1991)', 'Life Expectancy at Birth, female (1992)', 'Life Expectancy at Birth, female (1993)', 'Life Expectancy at Birth, female (1994)', 'Life Expectancy at Birth, female (1995)', 'Life Expectancy at Birth, female (1996)', 'Life Expectancy at Birth, female (1997)', 'Life Expectancy at Birth, female (1998)', 'Life Expectancy at Birth, female (1999)', 'Life Expectancy at Birth, female (2000)', 'Life Expectancy at Birth, female (2001)', 'Life Expectancy at Birth, female (2002)', 'Life Expectancy at Birth, female (2003)', 'Life Expectancy at Birth, female (2004)', 'Life Expectancy at Birth, female (2005)', 'Life Expectancy at Birth, female (2006)', 'Life Expectancy at Birth, female (2007)', 'Life Expectancy at Birth, female (2008)', 'Life Expectancy at Birth, female (2009)', 'Life Expectancy at Birth, female (2010)', 'Life Expectancy at Birth, female (2011)', 'Life Expectancy at Birth, female (2012)', 'Life Expectancy at Birth, female (2013)', 'Life Expectancy at Birth, female (2014)', 'Life Expectancy at Birth, female (2015)', 'Life Expectancy at Birth, female (2016)', 'Life Expectancy at Birth, female (2017)', 'Life Expectancy at Birth, female (2018)', 'Life Expectancy at Birth, female (2019)', 'Life Expectancy at Birth, female (2020)', 'Life Expectancy at Birth, female (2021)', 'Expected Years of Schooling, female (1990)', 'Expected Years of Schooling, female (1991)', 'Expected Years of Schooling, female (1992)', 'Expected Years of Schooling, female (1993)', 'Expected Years of Schooling, female (1994)', 'Expected Years of Schooling, female (1995)', 'Expected Years of Schooling, female (1996)', 'Expected Years of Schooling, female (1997)', 'Expected Years of Schooling, female (1998)', 'Expected Years of Schooling, female (1999)', 'Expected Years of Schooling, female (2000)', 'Expected Years of Schooling, female (2001)', 'Expected Years of Schooling, female (2002)', 'Expected Years of Schooling, female (2003)', 'Expected Years of Schooling, female (2004)', 'Expected Years of Schooling, female (2005)', 'Expected Years of Schooling, female (2006)', 'Expected Years of Schooling, female (2007)', 'Expected Years of Schooling, female (2008)', 'Expected Years of Schooling, female (2009)', 'Expected Years of Schooling, female (2010)', 'Expected Years of Schooling, female (2011)', 'Expected Years of Schooling, female (2012)', 'Expected Years of Schooling, female (2013)', 'Expected Years of Schooling, female (2014)', 'Expected Years of Schooling, female (2015)', 'Expected Years of Schooling, female (2016)', 'Expected Years of Schooling, female (2017)', 'Expected Years of Schooling, female (2018)', 'Expected Years of Schooling, female (2019)', 'Expected Years of Schooling, female (2020)', 'Expected Years of Schooling, female (2021)', 'Mean Years of Schooling, female (1990)', 'Mean Years of Schooling, female (1991)', 'Mean Years of Schooling, female (1992)', 'Mean Years of Schooling, female (1993)', 'Mean Years of Schooling, female (1994)', 'Mean Years of Schooling, female (1995)', 'Mean Years of Schooling, female (1996)', 'Mean Years of Schooling, female (1997)', 'Mean Years of Schooling, female (1998)', 'Mean Years of Schooling, female (1999)', 'Mean Years of Schooling, female (2000)', 'Mean Years of Schooling, female (2001)', 'Mean Years of Schooling, female (2002)', 'Mean Years of Schooling, female (2003)', 'Mean Years of Schooling, female (2004)', 'Mean Years of Schooling, female (2005)', 'Mean Years of Schooling, female (2006)', 'Mean Years of Schooling, female (2007)', 'Mean Years of Schooling, female (2008)', 'Mean Years of Schooling, female (2009)', 'Mean Years of Schooling, female (2010)', 'Mean Years of Schooling, female (2011)', 'Mean Years of Schooling, female (2012)', 'Mean Years of Schooling, female (2013)', 'Mean Years of Schooling, female (2014)', 'Mean Years of Schooling, female (2015)', 'Mean Years of Schooling, female (2016)', 'Mean Years of Schooling, female (2017)', 'Mean Years of Schooling, female (2018)', 'Mean Years of Schooling, female (2019)', 'Mean Years of Schooling, female (2020)', 'Mean Years of Schooling, female (2021)', 'Gross National Income Per Capita, female (1990)', 'Gross National Income Per Capita, female (1991)', 'Gross National Income Per Capita, female (1992)', 'Gross National Income Per Capita, female (1993)', 'Gross National Income Per Capita, female (1994)', 'Gross National Income Per Capita, female (1995)', 'Gross National Income Per Capita, female (1996)', 'Gross National Income Per Capita, female (1997)', 'Gross National Income Per Capita, female (1998)', 'Gross National Income Per Capita, female (1999)', 'Gross National Income Per Capita, female (2000)', 'Gross National Income Per Capita, female (2001)', 'Gross National Income Per Capita, female (2002)', 'Gross National Income Per Capita, female (2003)', 'Gross National Income Per Capita, female (2004)', 'Gross National Income Per Capita, female (2005)', 'Gross National Income Per Capita, female (2006)', 'Gross National Income Per Capita, female (2007)', 'Gross National Income Per Capita, female (2008)', 'Gross National Income Per Capita, female (2009)', 'Gross National Income Per Capita, female (2010)', 'Gross National Income Per Capita, female (2011)', 'Gross National Income Per Capita, female (2012)', 'Gross National Income Per Capita, female (2013)', 'Gross National Income Per Capita, female (2014)', 'Gross National Income Per Capita, female (2015)', 'Gross National Income Per Capita, female (2016)', 'Gross National Income Per Capita, female (2017)', 'Gross National Income Per Capita, female (2018)', 'Gross National Income Per Capita, female (2019)', 'Gross National Income Per Capita, female (2020)', 'Gross National Income Per Capita, female (2021)', 'HDI male (1990)', 'HDI male (1991)', 'HDI male (1992)', 'HDI male (1993)', 'HDI male (1994)', 'HDI male (1995)', 'HDI male (1996)', 'HDI male (1997)', 'HDI male (1998)', 'HDI male (1999)', 'HDI male (2000)', 'HDI male (2001)', 'HDI male (2002)', 'HDI male (2003)', 'HDI male (2004)', 'HDI male (2005)', 'HDI male (2006)', 'HDI male (2007)', 'HDI male (2008)', 'HDI male (2009)', 'HDI male (2010)', 'HDI male (2011)', 'HDI male (2012)', 'HDI male (2013)', 'HDI male (2014)', 'HDI male (2015)', 'HDI male (2016)', 'HDI male (2017)', 'HDI male (2018)', 'HDI male (2019)', 'HDI male (2020)', 'HDI male (2021)', 'Life Expectancy at Birth, male (1990)', 'Life Expectancy at Birth, male (1991)', 'Life Expectancy at Birth, male (1992)', 'Life Expectancy at Birth, male (1993)', 'Life Expectancy at Birth, male (1994)', 'Life Expectancy at Birth, male (1995)', 'Life Expectancy at Birth, male (1996)', 'Life Expectancy at Birth, male (1997)', 'Life Expectancy at Birth, male (1998)', 'Life Expectancy at Birth, male (1999)', 'Life Expectancy at Birth, male (2000)', 'Life Expectancy at Birth, male (2001)', 'Life Expectancy at Birth, male (2002)', 'Life Expectancy at Birth, male (2003)', 'Life Expectancy at Birth, male (2004)', 'Life Expectancy at Birth, male (2005)', 'Life Expectancy at Birth, male (2006)', 'Life Expectancy at Birth, male (2007)', 'Life Expectancy at Birth, male (2008)', 'Life Expectancy at Birth, male (2009)', 'Life Expectancy at Birth, male (2010)', 'Life Expectancy at Birth, male (2011)', 'Life Expectancy at Birth, male (2012)', 'Life Expectancy at Birth, male (2013)', 'Life Expectancy at Birth, male (2014)', 'Life Expectancy at Birth, male (2015)', 'Life Expectancy at Birth, male (2016)', 'Life Expectancy at Birth, male (2017)', 'Life Expectancy at Birth, male (2018)', 'Life Expectancy at Birth, male (2019)', 'Life Expectancy at Birth, male (2020)', 'Life Expectancy at Birth, male (2021)', 'Expected Years of Schooling, male (1990)', 'Expected Years of Schooling, male (1991)', 'Expected Years of Schooling, male (1992)', 'Expected Years of Schooling, male (1993)', 'Expected Years of Schooling, male (1994)', 'Expected Years of Schooling, male (1995)', 'Expected Years of Schooling, male (1996)', 'Expected Years of Schooling, male (1997)', 'Expected Years of Schooling, male (1998)', 'Expected Years of Schooling, male (1999)', 'Expected Years of Schooling, male (2000)', 'Expected Years of Schooling, male (2001)', 'Expected Years of Schooling, male (2002)', 'Expected Years of Schooling, male (2003)', 'Expected Years of Schooling, male (2004)', 'Expected Years of Schooling, male (2005)', 'Expected Years of Schooling, male (2006)', 'Expected Years of Schooling, male (2007)', 'Expected Years of Schooling, male (2008)', 'Expected Years of Schooling, male (2009)', 'Expected Years of Schooling, male (2010)', 'Expected Years of Schooling, male (2011)', 'Expected Years of Schooling, male (2012)', 'Expected Years of Schooling, male (2013)', 'Expected Years of Schooling, male (2014)', 'Expected Years of Schooling, male (2015)', 'Expected Years of Schooling, male (2016)', 'Expected Years of Schooling, male (2017)', 'Expected Years of Schooling, male (2018)', 'Expected Years of Schooling, male (2019)', 'Expected Years of Schooling, male (2020)', 'Expected Years of Schooling, male (2021)', 'Mean Years of Schooling, male (1990)', 'Mean Years of Schooling, male (1991)', 'Mean Years of Schooling, male (1992)', 'Mean Years of Schooling, male (1993)', 'Mean Years of Schooling, male (1994)', 'Mean Years of Schooling, male (1995)', 'Mean Years of Schooling, male (1996)', 'Mean Years of Schooling, male (1997)', 'Mean Years of Schooling, male (1998)', 'Mean Years of Schooling, male (1999)', 'Mean Years of Schooling, male (2000)', 'Mean Years of Schooling, male (2001)', 'Mean Years of Schooling, male (2002)', 'Mean Years of Schooling, male (2003)', 'Mean Years of Schooling, male (2004)', 'Mean Years of Schooling, male (2005)', 'Mean Years of Schooling, male (2006)', 'Mean Years of Schooling, male (2007)', 'Mean Years of Schooling, male (2008)', 'Mean Years of Schooling, male (2009)', 'Mean Years of Schooling, male (2010)', 'Mean Years of Schooling, male (2011)', 'Mean Years of Schooling, male (2012)', 'Mean Years of Schooling, male (2013)', 'Mean Years of Schooling, male (2014)', 'Mean Years of Schooling, male (2015)', 'Mean Years of Schooling, male (2016)', 'Mean Years of Schooling, male (2017)', 'Mean Years of Schooling, male (2018)', 'Mean Years of Schooling, male (2019)', 'Mean Years of Schooling, male (2020)', 'Mean Years of Schooling, male (2021)', 'Gross National Income Per Capita, male (1990)', 'Gross National Income Per Capita, male (1991)', 'Gross National Income Per Capita, male (1992)', 'Gross National Income Per Capita, male (1993)', 'Gross National Income Per Capita, male (1994)', 'Gross National Income Per Capita, male (1995)', 'Gross National Income Per Capita, male (1996)', 'Gross National Income Per Capita, male (1997)', 'Gross National Income Per Capita, male (1998)', 'Gross National Income Per Capita, male (1999)', 'Gross National Income Per Capita, male (2000)', 'Gross National Income Per Capita, male (2001)', 'Gross National Income Per Capita, male (2002)', 'Gross National Income Per Capita, male (2003)', 'Gross National Income Per Capita, male (2004)', 'Gross National Income Per Capita, male (2005)', 'Gross National Income Per Capita, male (2006)', 'Gross National Income Per Capita, male (2007)', 'Gross National Income Per Capita, male (2008)', 'Gross National Income Per Capita, male (2009)', 'Gross National Income Per Capita, male (2010)', 'Gross National Income Per Capita, male (2011)', 'Gross National Income Per Capita, male (2012)', 'Gross National Income Per Capita, male (2013)', 'Gross National Income Per Capita, male (2014)', 'Gross National Income Per Capita, male (2015)', 'Gross National Income Per Capita, male (2016)', 'Gross National Income Per Capita, male (2017)', 'Gross National Income Per Capita, male (2018)', 'Gross National Income Per Capita, male (2019)', 'Gross National Income Per Capita, male (2020)', 'Gross National Income Per Capita, male (2021)', 'Inequality-adjusted Human Development Index (2010)', 'Inequality-adjusted Human Development Index (2011)', 'Inequality-adjusted Human Development Index (2012)', 'Inequality-adjusted Human Development Index

In [17]:
y = df["Human Development Index (2021)"]

In [18]:
features = [
    "Life Expectancy at Birth (2021)",
    "Expected Years of Schooling (2021)",
    "Mean Years of Schooling (2021)",
    "Gross National Income Per Capita (2021)"
]

X = df[features]

In [19]:
data = df[features + ["Human Development Index (2021)"]]

data = data.dropna()

X = data[features]
y = data["Human Development Index (2021)"]

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [21]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [22]:
y_pred = model.predict(X_test)

In [23]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score:", r2_score(y_test, y_pred))

MAE : 0.021855085852610947
MSE : 0.0011632731136127829
RMSE: 0.034106789846199
R2 Score: 0.9543524118083889

In [24]:
import pickle

pickle.dump(model, open("model.pkl", "wb"))

print("Model Saved Successfully!")

Model Saved Successfully!